[workspace]
members = [
    "core",
    "cli",
    "macro",
]
exclude = [
    "examples/",
]

[patch.crates-io]
scale-info = { git = "https://github.com/montekki/scale-info", branch = "fs-add-type-id" }
